### ISSUE TITLE
Two functions not define

### ISSUE THREAD

**Issue by O5-7** [shunchang-liu/PAP-Pytorch#1]
I cant find the define about this two funcation
init_patch_circle()
square_transform()
in pap_attack.py L149 and L151

**Comment by shunchang-liu** [comment]
> I cant find the define about this two funcation init_patch_circle() square_transform() in pap_attack.py L149 and L151

Thank you for pointing out the mistakes. Please use init_patch_square() and patch_transform() to replace init_patch_circle() and square_transform(), respectively.
